export default {
  CLIMBING: require('../../../images/categoriesImages/CLIMBING.jpg'),
  DANCING: require('../../../images/categoriesImages/DANCING.jpg'),
  KICKBOXING: require('../../../images/categoriesImages/KICKBOXING.jpg'),
  MARTIALARTS: require('../../../images/categoriesImages/MARTIALARTS.jpg'),
  PILATES: require('../../../images/categoriesImages/PILATES.jpg'),
  POWERLIFTING: require('../../../images/categoriesImages/POWERLIFTING.jpg'),
  RUNNING: require('../../../images/categoriesImages/RUNNING.jpg'),
  SWIMMING: require('../../../images/categoriesImages/SWIMMING.jpg'),
  TRX: require('../../../images/categoriesImages/TRX.jpg'),
  AEROBIC: require('../../../images/categoriesImages/AEROBIC.jpg'),
  BALANCEANDSTABILITY: require('../../../images/categoriesImages/BALANCEANDSTABILITY.jpg'),
  CROSSFIT: require('../../../images/categoriesImages/CROSSFIT.jpg'),
  CYCLING: require('../../../images/categoriesImages/CYCLING.jpg'),
  ENDURANCE: require('../../../images/categoriesImages/ENDURANCE.jpg'),
  YOGA: require('../../../images/categoriesImages/YOGA.jpg'),
  FLEXIBILITY: require('../../../images/categoriesImages/FLEXIBILITY.jpg'),
  HORSEBACKRIDING: require('../../../images/categoriesImages/HORSEBACKRIDING.jpg'),
  MUSCLEBUILDING: require('../../../images/categoriesImages/MUSCLEBUILDING.jpg'),
  STRENTH: require('../../../images/categoriesImages/STRENTH.jpg'),
  OTHER: require('../../../images/categoriesImages/OTHER.jpg')
};
